defaults:
  - _self_
  # compression config
  - compress: prune
  - eval: default

base_model: datasets/Llama-2-7b-hf
seqlen: -1 # -1 means native seqlen
verbose: False
run_name: test_compress


#paths to the various files
weight_path: ./models/${base_model}/original_weights
hessianDiag_path: ./models/${base_model}/hessianDiags/seed_0/pajama/128
save_path: ./models/${base_model}/compressed/${run_name}
temp_path: ./models/${base_model}/temp/${run_name}

seed: 0
add_bias: False
resume: False
log_wandb: False