hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
  output_subdir: .hydra
  verbose: true
  # 配置日志记录
  logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: NoWag.log
    root:
      level: INFO
      handlers: [console, file]
      propagate: true 